version: '3.7'

services:
  app:
    build: .
    ports:
      - 80:80
    replicas: 3

  load-balancer:
    image: nginx
    ports:
      - 9090:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

~

